apiVersion: v1
kind: Service
metadata:
    name: "testinged-73b2"
    labels:
        app: "testinged-73b2"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "testinged-73b2"