on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testinged.azurecr.io
        username: ${{ secrets.acr_testinged_username }}
        password: ${{ secrets.acr_testinged_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testinged.azurecr.io/testinged:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push testinged.azurecr.io/testinged:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testinged_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep frontend | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace frontend`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: frontend
        container-registry-url: testinged.azurecr.io
        container-registry-username: ${{ secrets.acr_testinged_username }}
        container-registry-password: ${{ secrets.acr_testinged_password }}
        secret-name: testingeddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: frontend
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          testinged.azurecr.io/testinged:${{ github.sha }}
        imagepullsecrets: |
          testingeddockerauth
